version: "3"

services:
  db:
    image: ghcr.io/kreneskyp/ix/postgres-pg-vector:15.3
    environment:
      POSTGRES_PASSWORD: ix
      POSTGRES_USER: ix
      POSTGRES_DB: ix
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    image: ghcr.io/kreneskyp/ix/sandbox:latest
    #image: ghcr.io/ix:latest
    command: uvicorn ix.server.asgi:application --host 0.0.0.0 --port 8001 --reload
    ports:
      - "8001:8001"
    links:
      - db
      - redis
    volumes:
      - .:/var/app
      #- .node_modules:/var/npm/node_modules
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
      - .ipython:/root/.ipython
    env_file:
      - .env
    environment:
      DJANGO_SETTINGS_MODULE: "ix.server.settings"

  nginx:
    image: nginx:latest
    ports:
      - "8000:8000"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./.compiled-static:/var/static/
    depends_on:
      - web

  worker:
    image: ghcr.io/kreneskyp/ix/sandbox:latest
    command: celery.sh
    links:
      - db
      - redis
    volumes:
      - .:/var/app
      - .node_modules:/var/npm/node_modules
      - ./bin:/usr/bin/ix
      - .bash_profile:/root/.bash_profile
    env_file:
      - .env


  redis:
    image: redis

